# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - r: oldrel
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: linux
      dist: trusty
      sudo: false
    - r: devel
      os: linux
      dist: trusty
      sudo: false
    - r: release
      os: osx

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
