# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stepFun <- function(x, nSteps, smoothSteps) {
    .Call('_ANN2_stepFun', PACKAGE = 'ANN2', x, nSteps, smoothSteps)
}

stepGradFun <- function(x, nSteps, smoothSteps) {
    .Call('_ANN2_stepGradFun', PACKAGE = 'ANN2', x, nSteps, smoothSteps)
}

lossFunction <- function(y, y_fit, lossType, dHuber) {
    .Call('_ANN2_lossFunction', PACKAGE = 'ANN2', y, y_fit, lossType, dHuber)
}

predictC <- function(NN, newdata, standardize) {
    .Call('_ANN2_predictC', PACKAGE = 'ANN2', NN, newdata, standardize)
}

stochGD <- function(dataList, nObs, standardize, y_center, y_scale, y_names, activTypes, lossType, dHuber, nSteps, smoothSteps, batchSize, maxEpochs, learnRate, momentum, L1, L2, earlyStop, earlyStopEpochs, earlyStopTol, lrSched, lrSchedEpochs, lrSchedLearnRates, fpOut, bpOut, upOut, validLoss, verbose, regression, plotExample) {
    .Call('_ANN2_stochGD', PACKAGE = 'ANN2', dataList, nObs, standardize, y_center, y_scale, y_names, activTypes, lossType, dHuber, nSteps, smoothSteps, batchSize, maxEpochs, learnRate, momentum, L1, L2, earlyStop, earlyStopEpochs, earlyStopTol, lrSched, lrSchedEpochs, lrSchedLearnRates, fpOut, bpOut, upOut, validLoss, verbose, regression, plotExample)
}

